---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-operator-lifecycle-manager
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-image-registry
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-marketplace
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-network-console
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-network-diagnostics
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
---
apiVersion: operator.openshift.io/v1
kind: DNS
metadata:
  name: default
spec:
  nodePlacement:
    tolerations:
    - effect: NoSchedule
      operator: Exists
---
