#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: create-admin-user
#  namespace: quay-enterprise
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
#metadata:
#  name: create-admin-user
#  namespace: quay-enterprise
#rules:
#- apiGroups:
#  - ""
#  resources:
#  - secrets
#  verbs:
#  - get
#  - list
#  - create
#  - patch
#  - update
#  - delete
#- apiGroups:
#  - route.openshift.io
#  resources:
#  - routes
#  verbs:
#  - get
#  - list
#- apiGroups:
#  - quay.redhat.com
#  resources:
#  - quayregistries
#  verbs:
#  - get
#  - list
#  - watch
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: create-admin-user
#  namespace: quay-enterprise
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: Role
#  name: create-admin-user
#subjects:
#- kind: ServiceAccount
#  name: create-admin-user
#  namespace: quay-enterprise
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: quay-config-bundle
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{- /* read the bucket data and endpoint access data */ -}}
    {{- $objBucket := (lookup "objectbucket.io/v1alpha1" "ObjectBucket" "" "obc-quay-enterprise-registry-quay") }}
    {{- $awsAccess := (lookup "v1" "Secret" "quay-enterprise" "registry-quay") }}
    {{- /* create the quay config file as a template */ -}}
    {{- $quayConfig := `
    DISTRIBUTED_STORAGE_CONFIG:
      default:
        - RadosGWStorage
        - access_key: %[1]s
          bucket_name: %[2]s
          hostname: rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc
          is_secure: true
          port: 443
          secret_key: %[3]s
          storage_path: /datastorage/registry-quay
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    DISTRIBUTED_STORAGE_PREFERENCE:
      - default
    AUTHENTICATION_TYPE: OIDC
    BANK_LOGIN_CONFIG:
      CLIENT_ID: quay-enterprise
      CLIENT_SECRET: GawvsAE1AnqPh7INeHgDmzBwTyHA4L8C
      OIDC_SERVER: https://keycloak.paas.woorifg.com:8143/realms/woori-realm/
      SERVICE_NAME: WooriBank SSO
      PREFERRED_GROUP_CLAIM_NAME: quay-group
      LOGIN_SCOPES: [ 'openid' ]
      OIDC_DISABLE_USER_ENDPOINT: false
    FEATURE_TEAM_SYNCING: true
    FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: true
    FEATURE_UI_V2: true
    DEFAULT_TAG_EXPIRATION: 2w
    PREFERRED_URL_SCHEME: http
    SERVER_HOSTNAME: registry.apps.paas.woorifg.com
    SETUP_COMPLETE: true
    SUPER_USERS:
      - quayadmin
    FEATURE_USER_CREATION: true
    FEATURE_USER_INITIALIZE: false
    FEATURE_SUPERUSERS_ORG_CREATION_ONLY: true
    FEATURE_SUPERUSERS_FULL_ACCESS: true
    FEATURE_RESTRICTED_USERS: false 
    RESTRICTED_USERS_WHITELIST:
      - quayadmin
    BROWSER_API_CALLS_XHR_ONLY: false
    TAG_EXPIRATION_OPTIONS:
      - 1d
      - 1w
      - 2w
      - 4w
    FEATURE_DIRECT_LOGIN: true
    }}

    {{- /* create the secret using the quay configuration template created above. */ -}}
    - complianceType: mustonlyhave
      objectDefinition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: init-config-bundle-secret
          namespace: quay-enterprise
        type: Opaque
        data:
          config.yaml: {{ (printf $quayConfig ($awsAccess.data.AWS_ACCESS_KEY_ID | base64dec) $objBucket.spec.endpoint.bucketName ($awsAccess.data.AWS_SECRET_ACCESS_KEY | base64dec)) | base64enc }}
---
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: quay-config-bundle
  components:
    - kind: clairpostgres
      managed: false
    - kind: postgres
      managed: true
    - kind: mirror
      managed: false
    - kind: horizontalpodautoscaler
      managed: false
    - kind: clair
      managed: false
    - kind: objectstorage
      managed: true
    - kind: redis
      managed: true
    - kind: route
      managed: true
    - kind: monitoring
      managed: true
    - kind: tls
      managed: true
    - kind: quay
      managed: true
      overrides:
        replicas: 1
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 2Gi
