---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-block-odf
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: cluster.ocs.openshift.io/openshift-storage
        operator: In
        values:
        - ""
  storageClassDevices:
  - devicePaths:
    - /dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:1:0
    storageClassName: localblock-odf
    volumeMode: Block
  tolerations:
  - effect: NoSchedule
    operator: Exists
    key: node.ocs.openshift.io/storage
status:
  conditions:
    - status: "True"
      type: Available
---
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  plugins:
  - odf-console
