---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-release-channel
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{- if eq (lookup "cluster.open-cluster-management.io/v1alpha1" "ClusterClaim" "" "policies.release-channel").kind "ClusterClaim" }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: config.openshift.io/v1
        kind: ClusterVersion
        metadata:
          name: version
        spec:
          channel: {{ fromClusterClaim "policies.release-channel" }}
    {{- end }}
---
