---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-workload-availability
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: node-healthcheck-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: Manual
  operatorGroup:
    name: openshift-workload-availability
    namespace: openshift-workload-availability
  subscription:
    name: node-healthcheck-operator
    namespace: openshift-workload-availability
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: self-node-remediation
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: Manual
  subscription:
    name: self-node-remediation
    namespace: openshift-workload-availability
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: cluster-logging
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: Manual
  operatorGroup:
    name: openshift-logging
    namespace: openshift-logging
  subscription:
    name: cluster-logging
    namespace: openshift-logging
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops-operator
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: openshift-gitops-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: Manual
  operatorGroup:
    name: openshift-gitops-operator
    namespace: openshift-gitops-operator
  subscription:
    name: openshift-gitops-operator
    namespace: openshift-gitops-operator
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
