---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: install-operators-clean-og
spec:
  evaluationInterval:
    compliant: 1m
    noncompliant: 1m
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{- range $og := (lookup "operators.coreos.com/v1" "OperatorGroup" "" "" "policies.install").items }}
    {{- range $cg := (lookup "operators.coreos.com/v1" "OperatorGroup" $og.metadata.namespace "" "!policies.install").items }}
    - complianceType: mustnothave
      objectDefinition:
        apiVersion: operators.coreos.com/v1
        kind: OperatorGroup
        metadata:
          name: {{ $cg.metadata.name }}
          namespace: {{ $cg.metadata.namespace }}
    {{- end }}
    {{- end }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-kube-storage-version-migrator
  annotations:
    openshift.io/node-selector: node-role.kubernetes.io/master=
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-network-console
  annotations:
    openshift.io/node-selector: node-role.kubernetes.io/infra=
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-logging
  namespace: openshift-logging
  labels:
    policies.install: ""
spec:
  targetNamespaces:
  - openshift-logging
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
  labels:
    policies.install: ""
spec:
  name: cluster-logging
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
    - effect: NoSchedule
      operator: Exists
      key: node-role.kubernetes.io/infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-workload-availability
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-workload-availability
  namespace: openshift-workload-availability
  labels:
    policies.install: ""
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: node-healthcheck-operator
  namespace: openshift-workload-availability
  labels:
    policies.install: ""
spec:
  name: node-healthcheck-operator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
    - effect: NoSchedule
      operator: Exists
      key: node-role.kubernetes.io/infra
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: self-node-remediation
  namespace: openshift-workload-availability
  labels:
    policies.install: ""
spec:
  name: self-node-remediation
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
    - effect: NoSchedule
      operator: Exists
      key: node-role.kubernetes.io/infra
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: node-maintenance-operator
  namespace: openshift-workload-availability
  labels:
    policies.install: ""
spec:
  name: node-maintenance-operator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
    - effect: NoSchedule
      operator: Exists
      key: node-role.kubernetes.io/infra
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: install-operators-extra
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{hub if ne "none" (index .ManagedClusterLabels "policies.extra") hub}}
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: openshift-nmstate
          annotations:
            scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1
        kind: OperatorGroup
        metadata:
          name: openshift-nmstate
          namespace: openshift-nmstate
          labels:
            policies.install: ""
        spec:
          targetNamespaces:
          - openshift-nmstate
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: kubernetes-nmstate-operator
          namespace: openshift-nmstate
          labels:
            policies.install: ""
        spec:
          name: kubernetes-nmstate-operator
          source: cs-redhat-operator-index
          sourceNamespace: openshift-marketplace
          config:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - effect: NoSchedule
              operator: Exists
              key: node-role.kubernetes.io/infra
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: openshift-gitops-operator
          annotations:
            scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: openshift-gitops
          annotations:
            openshift.io/node-selector: node-role.kubernetes.io/infra=
            scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1
        kind: OperatorGroup
        metadata:
          name: openshift-gitops-operator
          namespace: openshift-gitops-operator
          labels:
            policies.install: ""
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: openshift-gitops-operator
          namespace: openshift-gitops-operator
          labels:
            policies.install: ""
        spec:
          name: openshift-gitops-operator
          source: cs-redhat-operator-index
          sourceNamespace: openshift-marketplace
          config:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - effect: NoSchedule
              operator: Exists
              key: node-role.kubernetes.io/infra
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: openshift-operators
          annotations:
            scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: servicemeshoperator
          namespace: openshift-operators
          labels:
            policies.install: ""
        spec:
          name: servicemeshoperator
          source: cs-redhat-operator-index
          sourceNamespace: openshift-marketplace
          config:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - effect: NoSchedule
              operator: Exists
              key: node-role.kubernetes.io/infra
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: kiali-ossm
          namespace: openshift-operators
          labels:
            policies.install: ""
            policies.stable: ""
        spec:
          channel: stable
          name: kiali-ossm
          source: cs-redhat-operator-index
          sourceNamespace: openshift-marketplace
          config:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - effect: NoSchedule
              operator: Exists
              key: node-role.kubernetes.io/infra
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: openshift-distributed-tracing
          annotations:
            scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1
        kind: OperatorGroup
        metadata:
          name: openshift-distributed-tracing
          namespace: openshift-distributed-tracing
          labels:
            policies.install: ""
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: jaeger-product
          namespace: openshift-distributed-tracing
          labels:
            policies.install: ""
        spec:
          name: jaeger-product
          source: cs-redhat-operator-index
          sourceNamespace: openshift-marketplace
          config:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - effect: NoSchedule
              operator: Exists
              key: node-role.kubernetes.io/infra
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: web-terminal
          namespace: openshift-operators
          labels:
            policies.install: ""
        spec:
          name: web-terminal
          source: cs-redhat-operator-index
          sourceNamespace: openshift-marketplace
          config:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - effect: NoSchedule
              operator: Exists
              key: node-role.kubernetes.io/infra
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: devworkspace-operator
          namespace: openshift-operators
          labels:
            policies.install: ""
        spec:
          name: devworkspace-operator
          source: cs-redhat-operator-index
          sourceNamespace: openshift-marketplace
          config:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - effect: NoSchedule
              operator: Exists
              key: node-role.kubernetes.io/infra
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: openshift-tempo-operator
          annotations:
            scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1
        kind: OperatorGroup
        metadata:
          name: openshift-tempo-operator
          namespace: openshift-tempo-operator
          labels:
            policies.install: ""
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: tempo-product
          namespace: openshift-tempo-operator
          labels:
            policies.install: ""
        spec:
          name: tempo-product
          source: cs-redhat-operator-index
          sourceNamespace: openshift-marketplace
          config:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - effect: NoSchedule
              operator: Exists
              key: node-role.kubernetes.io/infra
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: openshift-opentelemetry-operator
          annotations:
            scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1
        kind: OperatorGroup
        metadata:
          name: openshift-opentelemetry-operator
          namespace: openshift-opentelemetry-operator
          labels:
            policies.install: ""
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: opentelemetry-product
          namespace: openshift-opentelemetry-operator
          labels:
            policies.install: ""
        spec:
          name: opentelemetry-product
          source: cs-redhat-operator-index
          sourceNamespace: openshift-marketplace
          config:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - effect: NoSchedule
              operator: Exists
              key: node-role.kubernetes.io/infra
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: openshift-netobserv-operator
          annotations:
            scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Exists","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1
        kind: OperatorGroup
        metadata:
          name: openshift-netobserv-operator
          namespace: openshift-netobserv-operator
          labels:
            policies.install: ""
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: netobserv-operator
          namespace: openshift-netobserv-operator
          labels:
            policies.install: ""
        spec:
          name: netobserv-operator
          source: cs-redhat-operator-index
          sourceNamespace: openshift-marketplace
          config:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - effect: NoSchedule
              operator: Exists
              key: node-role.kubernetes.io/infra
    {{hub end hub}}
---
