apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-hub
  namespace: policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: vendor, operator: In, values: ["OpenShift"]}
          - {key: "local-cluster", operator: In, values: ["true"]}
          - {key: "policies.undeploy", operator: DoesNotExist}
          - {key: "policies.lite", operator: DoesNotExist}
