apiVersion: v1
kind: ConfigMap
metadata:
  name: quay-config
  namespace: policies
data:
  host: '{{ (lookup "route.openshift.io/v1" "Route" "openshift-quay" "quay-registry-quay" ).spec.host }}'
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: quay
spec:
  applicationMenu:
    section: Red Hat applications
    imageURL: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/OpenShift-LogoType.svg'
  href: 'https://{{ (lookup "route.openshift.io/v1" "Route" "openshift-quay" "quay-registry-quay" ).spec.host }}'
  location: ApplicationMenu
  text: 'Red Hat Quay Enterprise Registry'
---
