apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-quay
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-admin-user
  namespace: openshift-quay
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-admin-user
  namespace: openshift-quay
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
- apiGroups:
  - quay.redhat.com
  resources:
  - quayregistries
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-admin-user
  namespace: openshift-quay
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-admin-user
subjects:
- kind: ServiceAccount
  name: create-admin-user
  namespace: openshift-quay
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: operatorpolicy-quay-operator
  labels:
    operators.coreos.com/quay-operator.openshift-quay: ""
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: None
  operatorGroup:
    name: openshift-quay
    namespace: openshift-quay
    targetNamespaces:
      - openshift-quay
  subscription:
    name: quay-operator
    namespace: openshift-quay
    source: redhat-operators
    sourceNamespace: openshift-marketplace
---
apiVersion: v1
data:
  config.yaml: RkVBVFVSRV9VU0VSX0lOSVRJQUxJWkU6IHRydWUKQlJPV1NFUl9BUElfQ0FMTFNfWEhSX09OTFk6IGZhbHNlClNVUEVSX1VTRVJTOgotIHF1YXlhZG1pbgpGRUFUVVJFX1VTRVJfQ1JFQVRJT046IHRydWUKRkVBVFVSRV9TVVBFUlVTRVJTX0ZVTExfQUNDRVNTOiB0cnVlCg==
kind: Secret
metadata:
  name: init-config-bundle-secret
  namespace: openshift-quay
type: Opaque
---
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: registry
  namespace: openshift-quay
spec:
  configBundleSecret: init-config-bundle-secret
  components:
    - kind: objectstorage
      managed: true
    - managed: true
      kind: tls
