apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-opp
placementBindingDefaults:
  name: binding-policy-hub
policyDefaults:
  categories:
  controls:
  standards:
  namespace: policies
  policySets:
  - hub
  remediationAction: enforce
  severity: medium
policies:
# Hub Operators Policies - start
- name: install-operators-hub
  manifests:
  - path: install/install-operators-hub.yaml
  policySets:
  - hub
# Hub Operators Policies - end
# All Operators Policies - start
- name: install-operators
  manifests:
  - path: install/install-operators.yaml
  policySets:
  - hub
  - managed
# All Operators Policies - end
# Subscription Init Policies - start
- name: upgrade-sub-init
  dependencies:
  - name: install-operators
  - name: config-operators
  manifests:
  - path: upgrade/upgrade-sub-manual.yaml
  policySets:
  - sub-init
# Subscription Init Policies - end
# Manual Subscription Policies - start
- name: upgrade-sub-manual
  manifests:
  - path: upgrade/upgrade-sub-manual.yaml
  policySets:
  - sub-manual
# Manual Subscription Policies - end
# Automatic Subscription Policies - start
- name: upgrade-sub-automatic
  dependencies:
  - name: check-cv
  complianceType: mustonlyhave
  manifests:
  - path: upgrade/upgrade-sub-automatic.yaml
  policySets:
  - sub-automatic
# Automatic Subscription Policies - end
# cs-redhat operator update Policies - start
- name: upgrade-cs-redhat-operator
  complianceType: musthave
  dependencies:
  - name: check-cv
  manifests:
  - path: upgrade/upgrade-cs-redhat-operator.yaml
  policySets:
  - sub-automatic
# cs-redhat operator update Policies - end
# Create Router Bundle Policies - start
- name: proxy-sync-hub
  dependencies:
  - name: check-cv
  manifests:
  - path: proxy/proxy-sync-hub.yaml
  policySets:
  - hub
# Create Router Bundle Policies - end
# Proxy Router Bundle Policies - start
- name: proxy-sync-managed
  dependencies:
  - name: check-cv
  manifests:
  - path: proxy/proxy-sync-managed.yaml
  policySets:
  - managed
# Proxy Router Bundle Policies - end
# Config  operators Policies - start
- name: config-operators
  dependencies:
  - name: check-cv
  - name: check-csv
  manifests:
  - path: config/config-operators.yaml
  policySets:
  - hub
  - managed
# Config operators Policies - end
# Config operators hub Policies - start
- name: config-operators-hub
  manifests:
  - path: config/config-operators-hub.yaml
  policySets:
  - hub
# Config operators hub Policies - end
# Config operators managed Policies - start
- name: config-operators-managed
  manifests:
  - path: config/config-operators-managed.yaml
  policySets:
  - managed
# Config operators managed Policies - end
# CV check Policies - start
- name: check-cv
  complianceType: mustnothave
  manifests:
  - path: check/check-cv.yaml
  policySets:
  - hub
  - managed
  remediationAction: inform
# Upgradeable check Policies - end
# CV check Policies - start
- name: check-upgradeable
  complianceType: mustnothave
  dependencies:
  - name: check-cv
  manifests:
  - path: check/check-upgradeable.yaml
  policySets:
  - hub
  - managed
  remediationAction: inform
# Upgradeable check Policies - end
# CSV check Policies - start
- name: check-csv
  manifests:
  - path: check/check-csv.yaml
  policySets:
  - hub
  - managed
  remediationAction: inform
# CSV check Policies - end
# infra label Policies - start
- name: node-infra-label
  manifests:
  - path: node/node-infra-label.yaml
  policySets:
  - hub
  - managed
  remediationAction: enforce
# infra label Policies - end
# infra toleration Policies - start
- name: node-infra-toleration
  evaluationInterval:
    compliant: never
    noncompliant: 1m
  manifests:
  - path: node/node-infra-toleration.yaml
  policySets:
  - hub
  - managed
  remediationAction: enforce
# infra toleration Policies - end
# infra mcp Policies - start
- name: node-infra-mcp
  evaluationInterval:
    compliant: never
    noncompliant: 1m
  manifests:
  - path: node/node-infra-mcp.yaml
  policySets:
  - hub
  - managed
  remediationAction: enforce
# infra mcp Policies - end
# signatures cm Policies - start
- name: upgrade-signatures
  manifests:
  - path: upgrade/upgrade-signatures.yaml
  policySets:
  - hub
  - managed
  remediationAction: enforce
# signatures cm Policies - end
# admin-acks cm Policies - start
- name: upgrade-admin-acks
  manifests:
  - path: upgrade/upgrade-admin-acks.yaml
  policySets:
  - hub
  - managed
  remediationAction: enforce
# admin-acks cm Policies - end
# marketplace jobs Policies - start
- name: upgrade-marketplace-job
  dependencies:
  - name: check-cv
  manifests:
  - path: upgrade/upgrade-marketplace-job.yaml
  policySets:
  - sub-automatic
  remediationAction: enforce
# marketplace jobs Policies - end
# upgrade upstream Policies - start
- name: upgrade-upstream
  dependencies:
  - name: install-operators
  manifests:
  - path: upgrade/upgrade-upstream.yaml
  policySets:
  - hub
  - managed
  remediationAction: enforce
# upgrade upstream Policies - end
# upgrade release channel Policies - start
- name: upgrade-release-channel
  dependencies:
  - name: check-cv
  manifests:
  - path: upgrade/upgrade-release-channel.yaml
  policySets:
  - hub
  - managed
  remediationAction: enforce
# upgrade release channel Policies - end
policySets:
  - name: hub
    placement:
      placementPath: placement/placement-hub.yaml
  - name: managed
    placement:
      placementPath: placement/placement-managed.yaml
  - name: sub-manual
    placement:
      placementPath: placement/placement-sub-manual.yaml
  - name: sub-automatic
    placement:
      placementPath: placement/placement-sub-automatic.yaml
  - name: sub-init
    placement:
      placementPath: placement/placement-sub-init.yaml
