---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-signatures-create
spec:
  evaluationInterval:
    compliant: 2m
    noncompliant: 1m
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{hub if ne "" (index .ManagedClusterLabels "policies.osus") hub}}
    {{hub range $hcm := (lookup "v1" "ConfigMap" "policies" "" "release.openshift.io/verification-signatures").items hub}}
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: {{hub $hcm.metadata.name hub}}
          namespace: openshift-config-managed
          labels:
            release.openshift.io/verification-signatures: ""
        binaryData: {{hub $hcm.binaryData | toRawJson hub}}
    {{hub end hub}}
    {{hub end hub}}
---
