---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-sub-automatic
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{- range $sub := (lookup "operators.coreos.com/v1alpha1" "Subscription" "" "" "!policies.ignore,policies.install").items }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: {{ $sub.metadata.name }}
          namespace: {{ $sub.metadata.namespace }}
        spec:
          installPlanApproval: Automatic
    {{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-sub-reset
spec:
  evaluationInterval:
    compliant: 5m
    noncompliant: 5m
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{- range $sub := (lookup "operators.coreos.com/v1alpha1" "Subscription" "" "" "!policies.ignore,policies.install").items }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: {{ $sub.metadata.name }}
          namespace: {{ $sub.metadata.namespace }}
        spec:
          channel:
    {{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-sub-remove-manual-ip
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{- range $sb := (lookup "operators.coreos.com/v1alpha1" "Subscription" "" "" "!policies.ignore,policies.install").items }}
    {{- range $ip := (lookup "operators.coreos.com/v1alpha1" "InstallPlan" $sb.metadata.namespace "").items }}
    {{- if contains (splitn "." 2 $sb.status.currentCSV)._0 (index $ip.spec.clusterServiceVersionNames 0) }}
    - complianceType: mustnothave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: InstallPlan
        metadata:
          name: {{ $ip.metadata.name }}
          namespace: {{ $ip.metadata.namespace }}
        spec:
          approval: Manual
          approved: false
    {{- end }}
    {{- end }}
    {{- end }}
---
