---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-signatures-create
spec:
  evaluationInterval:
    compliant: 2m
    noncompliant: 1m
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{hub if ne "" (index .ManagedClusterLabels "policies.osus") hub}}
    {{hub range $hcm := (lookup "v1" "ConfigMap" "policies" "" "release.openshift.io/verification-signatures").items hub}}
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: {{hub $hcm.metadata.name hub}}
          namespace: openshift-config-managed
          labels:
            release.openshift.io/verification-signatures: ""
        binaryData: {{hub $hcm.binaryData | toRawJson hub}}
    {{hub end hub}}
    {{hub end hub}}
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-signatures-delete
spec:
  evaluationInterval:
    compliant: 5m
    noncompliant: 5m
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{hub if ne "" (index .ManagedClusterLabels "policies.osus") hub}}
    {{hub if gt (len (lookup "v1" "ConfigMap" "policies" "" "release.openshift.io/verification-signatures").items) 0 hub}}
    {{- range $cm := (lookup "v1" "ConfigMap" "openshift-config-managed" "" "release.openshift.io/verification-signatures").items }}
    {{- if ne $cm.metadata.name "signatures-managed" }}
    {{- $not_exist := true }}
    {{hub range $hcm := (lookup "v1" "ConfigMap" "policies" "" "release.openshift.io/verification-signatures").items hub}}
    {{- if eq $cm.metadata.name "{{hub $hcm.metadata.name hub}}" }} {{ $not_exist = false }} {{ continue }} {{ end }}
    {{hub end hub}}
    {{- if $not_exist }}
    - complianceType: mustnothave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: {{ $cm.metadata.name }}
          namespace: openshift-config-managed
    {{- end }}
    {{- end }}
    {{- end }}
    {{hub end hub}}
    {{hub end hub}}
---
