---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-sub-automatic
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{- range $sub := (lookup "operators.coreos.com/v1alpha1" "Subscription" "" "" "!policies.ignore,policies.install").items }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: {{ $sub.metadata.name }}
          namespace: {{ $sub.metadata.namespace }}
        spec:
          installPlanApproval: Automatic
    {{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-sub-reset
spec:
  evaluationInterval:
    compliant: 10m
    noncompliant: 1m
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{- range $sub := (lookup "operators.coreos.com/v1alpha1" "Subscription" "" "" "!policies.ignore,policies.install").items }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: {{ $sub.metadata.name }}
          namespace: {{ $sub.metadata.namespace }}
        spec:
          channel:
    {{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-sub-remove-manual-ip
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{- range $sb := (lookup "operators.coreos.com/v1alpha1" "Subscription" "" "" "!policies.ignore,policies.install").items }}
    {{- range $ip := (lookup "operators.coreos.com/v1alpha1" "InstallPlan" $sb.metadata.namespace "").items }}
    {{- if contains (splitn "." 2 $sb.status.currentCSV)._0 (index $ip.spec.clusterServiceVersionNames 0) }}
    {{- if and (eq "Manual" $ip.spec.approval) (eq false $ip.spec.approved) }}
    - complianceType: mustnothave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: InstallPlan
        metadata:
          name: {{ $ip.metadata.name }}
          namespace: {{ $ip.metadata.namespace }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-sub-remove-unpack
spec:
  evaluationInterval:
    compliant: 10m
    noncompliant: 2m
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{- range $sb := (lookup "operators.coreos.com/v1alpha1" "Subscription" "" "" "!policies.ignore,policies.install").items }}
    {{- range $cd := (lookup "operators.coreos.com/v1alpha1" "Subscription" $sb.metadata.namespace $sb.metadata.name).status.conditions }}
    {{- if and (eq "BundleUnpackFailed" $cd.type) (eq "True" $cd.status) }}
    - complianceType: mustnothave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: {{ $sb.metadata.name }}
          namespace: {{ $sb.metadata.namespace }}
    {{- end }}
    {{- end }}
    {{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-sub-remove-failed
spec:
  evaluationInterval:
    compliant: 10m
    noncompliant: 5m
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{- range $sb := (lookup "operators.coreos.com/v1alpha1" "Subscription" "" "" "!policies.ignore,policies.install").items }}
    {{- range $cd := (lookup "operators.coreos.com/v1alpha1" "Subscription" $sb.metadata.namespace $sb.metadata.name).status.conditions }}
    {{- if and (or (eq "ResolutionFailed" $cd.type) (eq "InstallPlanFailed" $cd.type)) (eq "True" $cd.status) }}
    - complianceType: mustnothave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: {{ $sb.metadata.name }}
          namespace: {{ $sb.metadata.namespace }}
    {{- range $csv := (lookup "operators.coreos.com/v1alpha1" "ClusterServiceVersion" $sb.metadata.namespace "" "!olm.copiedFrom").items }}
    {{- range $pr := (index $csv.metadata.annotations "operatorframework.io/properties" | fromJson).properties }}
    {{- if and (eq "olm.package" $pr.type) (eq $sb.spec.name $pr.value.packageName) }}
    - complianceType: mustnothave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        metadata:
          name: {{ $csv.metadata.name }}
          namespace: {{ $csv.metadata.namespace }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
---
