apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocs-operator
  namespace: openshift-storage
status:
  conditions:
    - status: "True"
      type: Available
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-rgw-ocs-storagecluster-cephobjectstore-a
  namespace: openshift-storage
status:
  conditions:
    - status: "True"
      type: Available
---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
status:
  phase: Ready
---
