---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-sub-init
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{hub- if eq "Secret" (lookup "v1" "Secret" .ManagedClusterName "auto-import-secret").kind hub}}
    {{- range $sub := (lookup "operators.coreos.com/v1alpha1" "Subscription" "" "" "!policies.ignore,policies.install").items }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: {{ $sub.metadata.name }}
          namespace: {{ $sub.metadata.namespace }}
        spec:
          installPlanApproval: Manual
    {{- end }}
    {{hub- end hub}}
---
