---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-release-channel
spec:
  evaluationInterval:
    compliant: 30m
    noncompliant: 2m
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{hub if ne "" (index .ManagedClusterLabels "policies.release-channel") hub}}
    - complianceType: musthave
      objectDefinition:
        apiVersion: config.openshift.io/v1
        kind: ClusterVersion
        metadata:
          name: version
        spec:
          channel: {{hub index .ManagedClusterLabels "policies.release-channel" hub}}
    {{hub end hub}}
---
