---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-admin-acks
spec:
  evaluationInterval:
    compliant: 2m
    noncompliant: 1m
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{hub- if and (ne "" (index .ManagedClusterLabels "policies.osus")) (ne "" (index .ManagedClusterLabels "openshiftVersion-major-minor")) hub}}
    {{- $ov := semver (fromClusterClaim "version.openshift.io") }}
    {{- $kv := semver (fromClusterClaim "kubeversion.open-cluster-management.io") }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: admin-acks
          namespace: openshift-config
        data:
          ack-{{ $ov.Major }}.{{ $ov.Minor }}-kube-{{ $kv.Major }}.{{ add 1 $kv.Minor }}-api-removals-in-{{ $ov.Major }}.{{ add 1 $ov.Minor }}: "true"
    {{hub- end hub}}
---
