---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: upgrade-release-force
spec:
  evaluationInterval:
    compliant: 1m
    noncompliant: 1m
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{hub- if eq "true" (index .ManagedClusterLabels "policies.release-force") hub}}
    {{- if ne (lookup "config.openshift.io/v1" "ClusterVersion" "" "version").spec.desiredUpdate.version (lookup "config.openshift.io/v1" "ClusterVersion" "" "version").status.desired.version }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: config.openshift.io/v1
        kind: ClusterVersion
        metadata:
          name: version
        spec:
          desiredUpdate:
            force: true
    {{- end }}
    {{hub- end hub}}
---
