#apiVersion: v1
#kind: Namespace
#metadata:
#  name: openshift-compliance
#---
#apiVersion: policy.open-cluster-management.io/v1beta1
#kind: OperatorPolicy
#metadata:
#  name: compliance-operator
#spec:
#  remediationAction: enforce
#  severity: high
#  complianceType: musthave
#  upgradeApproval: Automatic
#  operatorGroup:
#    name: openshift-compliance
#    namespace: openshift-compliance
#    targetNamespaces:
#      - openshift-compliance
#  subscription:
#    name: compliance-operator
#    namespace: openshift-compliance
#    source: cs-redhat-operator-index
#    sourceNamespace: openshift-marketplace
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: rhacs-operator
#---
#apiVersion: policy.open-cluster-management.io/v1beta1
#kind: OperatorPolicy
#metadata:
#  name: rhacs-operator
#spec:
#  remediationAction: enforce
#  severity: high
#  complianceType: musthave
#  upgradeApproval: Automatic
#  operatorGroup:
#    name: rhacs-operator
#    namespace: rhacs-operator
#  subscription:
#    name: rhacs-operator
#    namespace: rhacs-operator
#    source: cs-redhat-operator-index
#    sourceNamespace: openshift-marketplace
#---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-workload-availability
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: node-healthcheck-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: Automatic
  operatorGroup:
    name: openshift-workload-availability
    namespace: openshift-workload-availability
  subscription:
    name: node-healthcheck-operator
    namespace: openshift-workload-availability
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: self-node-remediation
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: Automatic
  operatorGroup:
    name: openshift-workload-availability
    namespace: openshift-workload-availability
  subscription:
    name: self-node-remediation
    namespace: openshift-workload-availability
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: cluster-logging
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: Automatic
  operatorGroup:
    name: openshift-logging
    namespace: openshift-logging
  subscription:
    name: cluster-logging
    namespace: openshift-logging
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
