---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: node-infra-label-remove
spec:
  evaluationInterval:
    compliant: 1m
    noncompliant: 1m
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{- range $no := (lookup "v1" "Node" "" "" "!node-role.kubernetes.io/master,!node-role.kubernetes.io/infra,node-role.kubernetes.io/worker").items }}
    {{- if (regexMatch "^[a-z]*inf" $no.metadata.name) }}
    {{- if not (hasKey $no.metadata.annotations "policies.done") }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Node
        metadata:
          name: {{ $no.metadata.name }}
          labels:
            node-role.kubernetes.io/worker:
        spec:
          taints:
          - effect: NoSchedule
            key: node-role.kubernetes.io/infra
    {{- end }}
    {{- end }}
    {{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: node-infra-label-add
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    {{- range $no := (lookup "v1" "Node" "" "" "!node-role.kubernetes.io/master,!node-role.kubernetes.io/infra,!node-role.kubernetes.io/worker").items }}
    {{- if (regexMatch "^[a-z]*inf" $no.metadata.name) }}
    {{- if not (hasKey $no.metadata.annotations "policies.done") }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Node
        metadata:
          name: {{ $no.metadata.name }}
          annotations:
            policies.done: {{ now }}
          labels:
            kubernetes.io/hostname: {{ $no.metadata.name }}
            node-role.kubernetes.io/infra: ""
            node.openshift.io/os_id: rhcos
    {{- end }}
    {{- end }}
    {{- end }}
---
