---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: config-cluster-management-addon
spec:
  remediationAction: enforce
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 10m
  object-templates-raw: |
    {{- range $mca := (lookup "addon.open-cluster-management.io/v1alpha1" "ManagedClusterAddOn" "" "").items }}
    {{- if ne "local-cluster" $mca.metadata.namespace }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: addon.open-cluster-management.io/v1alpha1
        kind: ManagedClusterAddOn
        metadata:
          name: {{ $mca.metadata.name }}
          namespace: {{ $mca.metadata.namespace }}
        spec:
          configs:
          - name: managed
            namespace: open-cluster-management-hub
            group: addon.open-cluster-management.io
            resource: addondeploymentconfigs
    {{- else }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: addon.open-cluster-management.io/v1alpha1
        kind: ManagedClusterAddOn
        metadata:
          name: {{ $mca.metadata.name }}
          namespace: {{ $mca.metadata.namespace }}
        spec:
          configs:
          - name: hub
            namespace: open-cluster-management-hub
            group: addon.open-cluster-management.io
            resource: addondeploymentconfigs
    {{- end }}
    {{- end }}
---
apiVersion: remediation.medik8s.io/v1alpha1
kind: NodeHealthCheck
metadata:
  name: nodehealthcheck-acm
spec:
  minHealthy: 51%
  remediationTemplate:
    apiVersion: self-node-remediation.medik8s.io/v1alpha1
    name: self-node-remediation-automatic-strategy-template
    namespace: openshift-workload-availability
    kind: SelfNodeRemediationTemplate
  selector:
    matchExpressions:
    - key: node-role.kubernetes.io/acm
      operator: Exists
    - key: node-role.kubernetes.io/worker
      operator: DoesNotExist
    - key: node-role.kubernetes.io/infra
      operator: DoesNotExist
  unhealthyConditions:
  - type: Ready
    status: "False"
    duration: 300s
  - type: Ready
    status: Unknown
    duration: 300s
---
