---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: check-csv-latest
spec:
  evaluationInterval:
    compliant: 1m
    noncompliant: 1m
  remediationAction: inform
  severity: high
  object-templates-raw: |
    {{- range $sub := (lookup "operators.coreos.com/v1alpha1" "Subscription" "" "" "!policies.ignore,policies.install").items }}{{ $pkg := lookup "packages.operators.coreos.com/v1" "PackageManifest" "openshift-marketplace" $sub.spec.name }}
    {{- if eq "PackageManifest" $pkg.kind }}
    {{- range $chn := index $pkg.status.channels }}
    {{- if eq $pkg.status.defaultChannel $chn.name }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        metadata:
          name: {{ $chn.currentCSV }}
          namespace: {{ $sub.metadata.namespace }}
        status:
          phase: Succeeded
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
---
