---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: check-csv
spec:
  evaluationInterval:
    compliant: 5m
    noncompliant: 5m
  remediationAction: inform
  severity: high
  object-templates-raw: |
    {{- range $sub := (lookup "operators.coreos.com/v1alpha1" "Subscription" "" "" "!policies.ignore,policies.install").items }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        metadata:
          name: {{ $sub.status.currentCSV }}
          namespace: {{ $sub.metadata.namespace }}
        status:
          phase: Succeeded
    {{- end }}
---
