apiVersion: v1
kind: Namespace
metadata:
  name: openshift-local-storage
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-storage
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: operatorpolicy-local-storage-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: Automatic
  operatorGroup:
    name: openshift-local-storage
    namespace: openshift-local-storage
    targetNamespaces:
      - openshift-local-storage
  subscription:
    name: local-storage-operator
    namespace: openshift-local-storage
    source: redhat-operators
    sourceNamespace: openshift-marketplace
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: operatorpolicy-odf-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: Automatic
  operatorGroup:
    name: openshift-storage-operatorgroup
    namespace: openshift-storage
    targetNamespaces:
      - openshift-storage
  subscription:
    name: odf-operator
    namespace: openshift-storage
    source: redhat-operators
    sourceNamespace: openshift-marketplace
---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscovery
metadata:
  name: auto-discover-devices
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: cluster.ocs.openshift.io/openshift-storage
        operator: Exists
  tolerations:
  - effect: NoSchedule
    operator: Exists
    key: node-role.kubernetes.io/infra
---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: ocs-storagecluster
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: cluster.ocs.openshift.io/openshift-storage
        operator: Exists
  storageClassName: odf-blockvolume
  volumeMode: Block
  maxDeviceCount: 1
  deviceInclusionSpec:
    deviceTypes:
    - disk
    minSize: 1Ti
  tolerations:
  - effect: NoSchedule
    operator: Exists
    key: node-role.kubernetes.io/infra
---
apiVersion: odf.openshift.io/v1alpha1
kind: StorageSystem
metadata:
  name: ocs-storagecluster-storagesystem
  namespace: openshift-storage
spec:
  kind: storagecluster.ocs.openshift.io/v1
  name: ocs-storagecluster
  namespace: openshift-storage
---
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  plugins:
  - odf-console
