apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: policy-odf-cluster
spec:
  remediationAction: enforce
  severity: high
  object-templates-raw: |
    - complianceType: musthave
      objectDefinition:
        apiVersion: ocs.openshift.io/v1
        kind: StorageCluster
        metadata:
          annotations:
            uninstall.ocs.openshift.io/cleanup-policy: delete
            uninstall.ocs.openshift.io/mode: graceful
          name: ocs-storagecluster
          namespace: openshift-storage
        spec:
          flexibleScaling: true
          monDataDirHostPath: /var/lib/rook
          storageDeviceSets:
          - count: 1
            dataPVCTemplate:
              spec:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Ti
                storageClassName: odf-localvolumeset
                volumeMode: Block
            name: ocs-deviceset-localvolume
            replica: 3
          placement:
            all:
              tolerations:
              - effect: NoSchedule
                operator: Exists
                key: node-role.kubernetes.io/infra
            mds:
              tolerations:
              - effect: NoSchedule
                operator: Exists
                key: node-role.kubernetes.io/infra
            rgw:
              tolerations:
              - effect: NoSchedule
                operator: Exists
                key: node-role.kubernetes.io/infra
            noobaa-core::
              tolerations:
              - effect: NoSchedule
                operator: Exists
                key: node-role.kubernetes.io/infra
