apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-osus
  namespace: policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - {key: vendor, operator: In, values: ["OpenShift"]}
        - {key: "policies.undeploy", operator: DoesNotExist}
        - {key: "policies.osus", operator: Exists}
      claimSelector:
        matchExpressions:
        - {key: "policies.undeploy", operator: NotIn, values: ["true"]}
