apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-sub-manual
  namespace: policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - {key: vendor, operator: In, values: ["OpenShift"]}
        - {key: "policies.sub-approval", operator: In, values: ["manual","Manual"]}
      claimSelector:
        matchExpressions:
        - {key: "policies.undeploy", operator: NotIn, values: ["true"]}
