apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-sub-init
  namespace: policies
spec:
  predicates:
  - requiredClusterSelector:
      claimSelector:
        matchExpressions:
        - {key: "version.openshift.io", operator: DoesNotExist}
        - {key: "consoleurl.cluster.open-cluster-management.io", operator: DoesNotExist}
      labelSelector:
        matchExpressions:
        - {key: vendor, operator: In, values: ["OpenShift"]}
        - {key: "policies.undeploy", operator: DoesNotExist}
        - {key: "policies.sub-approval", operator: DoesNotExist}
