---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: cluster-logging
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: None
  operatorGroup:
    name: openshift-logging
    namespace: openshift-logging
    targetNamespaces:
    - openshift-logging
  subscription:
    name: cluster-logging
    namespace: openshift-logging
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: stackrox
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacs-operator
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: rhacs-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: None
  operatorGroup:
    name: rhacs-operator
    namespace: rhacs-operator
  subscription:
    name: rhacs-operator
    namespace: rhacs-operator
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-compliance
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: compliance-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: None
  operatorGroup:
    name: openshift-compliance
    namespace: openshift-compliance
    targetNamespaces:
    - openshift-compliance
  subscription:
    name: compliance-operator
    namespace: openshift-compliance
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: container-security-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: None
  subscription:
    name: container-security-operator
    namespace: openshift-operators
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-ingress-node-firewall
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: ingress-node-firewall
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: None
  operatorGroup:
    name: openshift-ingress-node-firewall
    namespace: openshift-ingress-node-firewall
  subscription:
    name: ingress-node-firewall
    namespace: openshift-ingress-node-firewall
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nmstate
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: kubernetes-nmstate-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: None
  operatorGroup:
    name: openshift-nmstate
    namespace: openshift-nmstate
    targetNamespaces:
    - openshift-nmstate
  subscription:
    name: kubernetes-nmstate-operator
    namespace: openshift-nmstate
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-workload-availability
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: node-healthcheck-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: None
  operatorGroup:
    name: openshift-workload-availability
    namespace: openshift-workload-availability
  subscription:
    name: node-healthcheck-operator
    namespace: openshift-workload-availability
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: self-node-remediation
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: None
  operatorGroup:
    name: openshift-workload-availability
    namespace: openshift-workload-availability
  subscription:
    name: self-node-remediation
    namespace: openshift-workload-availability
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: metallb-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: None
  operatorGroup:
    name: metallb-system
    namespace: metallb-system
  subscription:
    name: metallb-operator
    namespace: metallb-system
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-adp
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: redhat-oadp-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: None
  operatorGroup:
    name: openshift-adp
    namespace: openshift-adp
    targetNamespaces:
    - openshift-adp
  subscription:
    name: redhat-oadp-operator
    namespace: openshift-adp
    source: cs-redhat-operator-index
    sourceNamespace: openshift-marketplace
---
