apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-sub-init
  namespace: policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - {key: vendor, operator: In, values: ["OpenShift"]}
      claimSelector:
        matchExpressions:
        - {key: "policies.undeploy", operator: NotIn, values: ["true"]}
        - {key: "policies.sub-approval", operator: DoesNotExist}
